// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBank.Cards.Infrastructure.Persistence;

#nullable disable

namespace SmartBank.Cards.Infrastructure.Migrations
{
    [DbContext(typeof(CardsDbContext))]
    [Migration("20260920181049_InitialCards")]
    partial class InitialCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBank.BuildingBlocks.Infrastructure.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("SmartBank.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("SmartBank.Cards.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CvvEnc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cvv_enc");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_month");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_year");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("LastFour")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_four");

                    b.Property<string>("PanToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pan_token");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<int>("Brand")
                        .HasColumnType("integer")
                        .HasColumnName("card_brand");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_cards_customer");

                    b.HasIndex("AccountId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_cards_account_type");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("SmartBank.Cards.Domain.Card", b =>
                {
                    b.OwnsOne("SmartBank.BuildingBlocks.Domain.ValueObjects.Money", "DailyAtmLimit", b1 =>
                        {
                            b1.Property<Guid>("CardId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("atm_limit");

                            b1.HasKey("CardId");

                            b1.ToTable("cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");
                        });

                    b.OwnsOne("SmartBank.BuildingBlocks.Domain.ValueObjects.Money", "DailyEcommerceLimit", b1 =>
                        {
                            b1.Property<Guid>("CardId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("ecom_limit");

                            b1.HasKey("CardId");

                            b1.ToTable("cards");

                            b1.WithOwner()
                                .HasForeignKey("CardId");
                        });

                    b.Navigation("DailyAtmLimit")
                        .IsRequired();

                    b.Navigation("DailyEcommerceLimit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
