<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartBank.Ledger.Application\SmartBank.Ledger.Application.csproj" />
    <ProjectReference Include="..\SmartBank.Ledger.Domain\SmartBank.Ledger.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SmartBank.BuildingBlocks.Domain\SmartBank.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SmartBank.BuildingBlocks.Application\SmartBank.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SmartBank.BuildingBlocks.Infrastructure\SmartBank.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\SmartBank.BuildingBlocks.Web\SmartBank.BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\..\..\Contracts\SmartBank.Contracts.Grpc\SmartBank.Contracts.Grpc.csproj" />
  </ItemGroup>

</Project>
